FROM python:3.11-slim

RUN apt-get update && apt-get -y upgrade \
    && pip install --upgrade pip \
    && pip --version

RUN apt-get update && apt-get install -y procps \
    && rm -rf /var/lib/apt/lists/*

# Install mlflow dependencies:
WORKDIR /mlflow/

RUN pip install --no-cache-dir mlflow

# Expose mlflow ports
EXPOSE 5001